### ISSUE TITLE
Add purgecss support[Feature request]

### ISSUE THREAD

**Issue by FinnStolze** [mengxiong10/vue2-datepicker#471]
**What problem does this feature solve?**
Classes are added dynamically via javascript, which can not be identified by 
[purgecss whitelisting](https://github.com/FullHuman/purgecss-docs/blob/master/whitelisting.md)
Could you wrap your dynamic classes in index.css with 

/* purgecss start ignore */ 
.dynamic {
}
/* purgecss end ignore */

**Comment by xsdaniel** [comment]
This is actually a related question but probably could be an answer too.

I am using purgeCSS to include mx-*:

`whitelistPatternsChildren: [ /mx-.*$/ ]`

It works as expected. It keeps all the _vue2-datepicker_ classes, including all the dynamic ones. Problem is that I am using Tailwind. So purgeCSS is also including all those mx-* classes.

My question is: is there any way to set the prefix? Instead of _mx_, can I configure in some way any other string?

**Comment by mengxiong10** [comment]
You can create a scss file(e.g. test.scss) to replace default scss. 
```scss
$namespace: 'xmx'; // change the 'mx' to 'xmx'
@import '~vue2-datepicker/scss/index.scss';

```

```js
import './test.scss'
```

```html
<date-picker prefix-class="xmx" />
```
