### ISSUE TITLE
How do I open picker v.3.6.2 with custom button? 

### ISSUE THREAD

**Issue by FahrutdinovOF** [mengxiong10/vue2-datepicker#518]
Hi! I cant find any way to open date picker on button? And to hide input.

**Comment by mengxiong10** [comment]
use prop `open`.
```html
    <date-picker
      v-model="value"
      :open="open"  ></date-picker>
    <button @click="toggle">toggle</button>
```

```js
data() {
  return {
    open: false
  }
},
methods: {
   toggle () {
      this.open = !this.open
  }
}

```

**Comment by FahrutdinovOF** [comment]
Doesn't work with inline prop https://codepen.io/OlegF/pen/XWdPrjb

**Comment by mengxiong10** [comment]
You can use `v-show` when use `inline`.

**Comment by FahrutdinovOF** [comment]
If you use v-show, the calendar position floats left top :(

**Comment by mengxiong10** [comment]
You can use `style={ opacity: open ? '1' :'0'}`

**Comment by FahrutdinovOF** [comment]
Thank! You have a great vue kung fu.

**Comment by jan-scorl** [comment]
Hi :) I just wanted to add that if you want to hide the `input field`, it is probably better to use `visibility: hidden` instead of `opacity: 0`. If you use `opacity: 0` the mouse cursor will still change when you hover over the the space where the input field would normally be. If you use `visibility: hidden`,  it does not. Great date picker by the way, thank you!
